[package]
name = "closures-futures-asyn"
version = "0.1.0"
authors = ["Juciano C Barbosa <juciano.barbosa@sensedia.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
